name: CD Pipeline

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Append Database URL
        run: echo -e '\n\nspring.datasource.url=${{ secrets.DATABASE_URL }}' >> src/main/resources/application.properties

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/adamscript/tomateto-api
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tomateto-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/adamscript/tomateto-api:${{ needs.build.outputs.tags[0] }}