name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Testing
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: tomateto-db
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Append Database URL
        run: echo -e '\n\nspring.datasource.url=jdbc:postgresql://localhost:5432/tomateto-db?user=root&password=root' >> src/main/resources/application.properties
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Tests
        run: mvn -B test --file pom.xml
